title: jpa-schema-gradle-plugin
description: Gradle plugin for generate database schema or DDL scripts from JPA entities
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
  - jekyll-code-tabs
