title: jpa-schema-gradle-plugin
description: Gradle plugin for generate database schema or DDL scripts from JPA entities
google_analytics: 
show_downloads: true
theme: jekyll-theme-minima

gems:
  - jekyll-mentions
plugins:
  - jekyll-tabs
  - jekyll-remote-theme

