package io.github.divinespear.gradle.plugin

/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import groovy.sql.Sql

import java.sql.Types

import nebula.test.IntegrationSpec

class GenerateH2Spec extends IntegrationSpec {

    def setup() {
        buildFile << applyPlugin(JpaSchemaGeneratePlugin)
    }

    def shouldWorkEclipseLinkFormatted() {
        given:
        buildFile << """
            sourceSets {
                main {
                    java {
                        srcDir file("../../../../src/test/resources/unit/eclipselink/src")
                    }
                    resources {
                        srcDir file("../../../../src/test/resources/unit/eclipselink/resources")
                    }
                    output.resourcesDir output.classesDir
                }
            }
            
            generateSchema {
                format = true
                scriptAction = "drop-and-create"
                databaseProductName = "H2"
                databaseMajorVersion = 1
                databaseMinorVersion = 3
            }
        """
        when:
        runTasks "generateSchema"
        then:
        file("build/generated-schema/create.sql").exists()
        file("build/generated-schema/create.sql").text == """CREATE TABLE KEY_VALUE_STORE (
\tSTORED_KEY VARCHAR(128) NOT NULL,
\tCREATED_AT TIMESTAMP,
\tSTORED_VALUE VARCHAR(32768),
\tPRIMARY KEY (STORED_KEY)
);

CREATE TABLE MANY_COLUMN_TABLE (
\tID BIGINT NOT NULL,
\tCOLUMN00 VARCHAR,
\tCOLUMN01 VARCHAR,
\tCOLUMN02 VARCHAR,
\tCOLUMN03 VARCHAR,
\tCOLUMN04 VARCHAR,
\tCOLUMN05 VARCHAR,
\tCOLUMN06 VARCHAR,
\tCOLUMN07 VARCHAR,
\tCOLUMN08 VARCHAR,
\tCOLUMN09 VARCHAR,
\tCOLUMN10 VARCHAR,
\tCOLUMN11 VARCHAR,
\tCOLUMN12 VARCHAR,
\tCOLUMN13 VARCHAR,
\tCOLUMN14 VARCHAR,
\tCOLUMN15 VARCHAR,
\tCOLUMN16 VARCHAR,
\tCOLUMN17 VARCHAR,
\tCOLUMN18 VARCHAR,
\tCOLUMN19 VARCHAR,
\tCOLUMN20 VARCHAR,
\tCOLUMN21 VARCHAR,
\tCOLUMN22 VARCHAR,
\tCOLUMN23 VARCHAR,
\tCOLUMN24 VARCHAR,
\tCOLUMN25 VARCHAR,
\tCOLUMN26 VARCHAR,
\tCOLUMN27 VARCHAR,
\tCOLUMN28 VARCHAR,
\tCOLUMN29 VARCHAR,
\tPRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_GEN_SEQUENCE INCREMENT BY 50 START WITH 50;

"""
        file("build/generated-schema/drop.sql").exists()
        file("build/generated-schema/drop.sql").text == """DROP TABLE KEY_VALUE_STORE;

DROP TABLE MANY_COLUMN_TABLE;

DROP SEQUENCE SEQ_GEN_SEQUENCE;

"""
    }

    def shouldWorkHibernateFormatted() {
        given:
        buildFile << """
            sourceSets {
                main {
                    java {
                        srcDir file("../../../../src/test/resources/unit/hibernate/src")
                    }
                    resources {
                        srcDir file("../../../../src/test/resources/unit/hibernate/resources")
                    }
                    output.resourcesDir output.classesDir
                }
            }
            
            generateSchema {
                namingStrategy = "org.hibernate.cfg.ImprovedNamingStrategy"
                format = true
                scriptAction = "drop-and-create"
                databaseProductName = "H2"
                databaseMajorVersion = 1
                databaseMinorVersion = 3
            }
        """
        when:
        runTasks "generateSchema"
        then:
        file("build/generated-schema/create.sql").exists()
        file("build/generated-schema/create.sql").text == """create table key_value_store (
\tstored_key varchar(128) not null,
\tcreated_at timestamp,
\tstored_value varchar(32768),
\tprimary key (stored_key)
);

create table many_column_table (
\tid bigint generated by default as identity,
\tcolumn00 varchar(255),
\tcolumn01 varchar(255),
\tcolumn02 varchar(255),
\tcolumn03 varchar(255),
\tcolumn04 varchar(255),
\tcolumn05 varchar(255),
\tcolumn06 varchar(255),
\tcolumn07 varchar(255),
\tcolumn08 varchar(255),
\tcolumn09 varchar(255),
\tcolumn10 varchar(255),
\tcolumn11 varchar(255),
\tcolumn12 varchar(255),
\tcolumn13 varchar(255),
\tcolumn14 varchar(255),
\tcolumn15 varchar(255),
\tcolumn16 varchar(255),
\tcolumn17 varchar(255),
\tcolumn18 varchar(255),
\tcolumn19 varchar(255),
\tcolumn20 varchar(255),
\tcolumn21 varchar(255),
\tcolumn22 varchar(255),
\tcolumn23 varchar(255),
\tcolumn24 varchar(255),
\tcolumn25 varchar(255),
\tcolumn26 varchar(255),
\tcolumn27 varchar(255),
\tcolumn28 varchar(255),
\tcolumn29 varchar(255),
\tprimary key (id)
);

"""
        file("build/generated-schema/drop.sql").exists()
        file("build/generated-schema/drop.sql").text == """drop table key_value_store if exists;

drop table many_column_table if exists;

"""
    }
}
