package io.github.divinespear

import org.gradle.test.FunctionalSpec

class Issue5Spec extends FunctionalSpec {

    def setup() {
        buildFile << applyPlugin(JpaSchemaGeneratePlugin)
    }
    
    def shouldWorkHibernateWithValidationAPI() {
        given:
        buildFile << """
            sourceSets {
                main {
                    java {
                        srcDir file("../../../../src/test/resources/unit/hibernate/src")
                    }
                    resources {
                        srcDir file("../../../../src/test/resources/unit/hibernate/resources")
                    }
                    output.resourcesDir output.classesDir
                }
            }


            repositories {
                mavenCentral()
            }
            
            
            dependencies {
                compile 'org.hibernate:hibernate-entitymanager:4.3.4.Final'
                compile 'javax.validation:validation-api:1.1.0.Final'
                runtime 'org.hibernate:hibernate-validator:5.1.0.Final'
            }
            
            generateSchema {
                namingStrategy = "org.hibernate.cfg.ImprovedNamingStrategy"
                format = true
                scriptAction = "drop-and-create"
                databaseProductName = "H2"
                databaseMajorVersion = 1
                databaseMinorVersion = 3
            }
        """
        when:
        run "generateSchema"
        then:
        file("build/generated-schema/create.sql").exists()
        file("build/generated-schema/create.sql").text == """create table key_value_store (\r
\tstored_key varchar(128) not null,\r
\tcreated_at timestamp,\r
\tstored_value varchar(32768),\r
\tprimary key (stored_key)\r
);\r
\r
create table many_column_table (\r
\tid bigint generated by default as identity,\r
\tcolumn00 varchar(255),\r
\tcolumn01 varchar(255),\r
\tcolumn02 varchar(255),\r
\tcolumn03 varchar(255),\r
\tcolumn04 varchar(255),\r
\tcolumn05 varchar(255),\r
\tcolumn06 varchar(255),\r
\tcolumn07 varchar(255),\r
\tcolumn08 varchar(255),\r
\tcolumn09 varchar(255),\r
\tcolumn10 varchar(255),\r
\tcolumn11 varchar(255),\r
\tcolumn12 varchar(255),\r
\tcolumn13 varchar(255),\r
\tcolumn14 varchar(255),\r
\tcolumn15 varchar(255),\r
\tcolumn16 varchar(255),\r
\tcolumn17 varchar(255),\r
\tcolumn18 varchar(255),\r
\tcolumn19 varchar(255),\r
\tcolumn20 varchar(255),\r
\tcolumn21 varchar(255),\r
\tcolumn22 varchar(255),\r
\tcolumn23 varchar(255),\r
\tcolumn24 varchar(255),\r
\tcolumn25 varchar(255),\r
\tcolumn26 varchar(255),\r
\tcolumn27 varchar(255),\r
\tcolumn28 varchar(255),\r
\tcolumn29 varchar(255),\r
\tprimary key (id)\r
);\r
\r
"""
        file("build/generated-schema/drop.sql").exists()
        file("build/generated-schema/drop.sql").text == """drop table key_value_store if exists;\r
\r
drop table many_column_table if exists;\r
\r
"""
    }
}
